FROM almalinux:9
# CMD ["ping", "google.com"]
# ENTRYPOINT ["ping", "google.com"]

CMD [ "google.com" ]
ENTRYPOINT ["ping"]

# docker run entry:1.0.0 ping facebook.com
# docker ps -a --no-trunc  #Show full untruncated IDs:
